<a href="https://colab.research.google.com/github/filfish2007-cav/ITStep-AI/blob/superwised_learning/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модуля pandas

In [2]:
import pandas as pd

Дані про пасажирів корабля:
* pclass -- клас білета(перший, другий або третій)
* sex -- стать
* age -- вік
* sibsp -- кількість братів\сестер та чоловіків\дружин на борту
* parch -- кількість дітей та батьків на борту
* fare -- вартість поїздки
* embarked -- Порт посадки (C = Шербур, Q = Квінстаун, S = Саутгемптон)

In [14]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/ship_passengers.csv",
                 index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [6]:
df.head(10)

   pclass     sex   age  sibsp  parch     fare embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S
5       3    male   NaN      0      0   8.4583        Q
6       1    male  54.0      0      0  51.8625        S
7       3    male   2.0      3      1  21.0750        S
8       3  female  27.0      0      2  11.1333        S
9       2  female  14.0      1      0  30.0708        C

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   embarked  889 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 55.7+ KB

In [8]:
df.shape

(891, 7)

# Завдання 2
Скільки пасажирів сіло у Квінстауні?

In [15]:
mask = df['embarked'] == 'Q'

df[mask].shape

(77, 7)

In [17]:
mask.sum()

np.int64(77)

In [16]:
mask

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890     True
Name: embarked, Length: 891, dtype: bool

# Завдання 3
Виведіть стать, вік та вартість поїздки для пасажирів з білетом першого класу

In [21]:
result = df.loc[df['pclass'] == 1, ['sex', 'age', 'fare']]
result

        sex   age     fare
1    female  38.0  71.2833
3    female  35.0  53.1000
6      male  54.0  51.8625
11   female  58.0  26.5500
23     male  28.0  35.5000
..      ...   ...      ...
871  female  47.0  52.5542
872    male  33.0   5.0000
879  female  56.0  83.1583
887  female  19.0  30.0000
889    male  26.0  30.0000

[216 rows x 3 columns]

# Завдання 4
Ввиведіть дані про неповнолітніх чоловіків з Шербура

In [22]:
minors_from_cherbourg = df[
    (df['sex'] == 'male') &
    (df['age'] < 18) &
    (df['embarked'] == 'C')
]
minors_from_cherbourg

     pclass   sex    age  sibsp  parch      fare embarked
125       3  male  12.00      1      0   11.2417        C
352       3  male  15.00      1      1    7.2292        C
532       3  male  17.00      1      1    7.2292        C
550       1  male  17.00      0      2  110.8833        C
731       3  male  11.00      0      0   18.7875        C
803       3  male   0.42      0      1    8.5167        C
827       2  male   1.00      0      2   37.0042        C

# Завдання 5
Створіть новий стовпчик relatives -- загальна кількість родичів на борту для кожного пасажира

In [23]:
df['relatives'] = df['sibsp'] + df['parch']
df['relatives']

0      1
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    3
889    0
890    0
Name: relatives, Length: 891, dtype: int64

# Завдання 6
Видаліть стовпчик, в якому найбільше пропусків. Якщо пропущені значення ще залишаться, видаліть рядки з пропусками

In [26]:
new_df = df.drop('age',axis=1)

     pclass     sex  sibsp  parch     fare embarked  relatives
0         3    male      1      0   7.2500        S          1
1         1  female      1      0  71.2833        C          1
2         3  female      0      0   7.9250        S          0
3         1  female      1      0  53.1000        S          1
4         3    male      0      0   8.0500        S          0
..      ...     ...    ...    ...      ...      ...        ...
886       2    male      0      0  13.0000        S          0
887       1  female      0      0  30.0000        S          0
888       3  female      1      2  23.4500        S          3
889       1    male      0      0  30.0000        C          0
890       3    male      0      0   7.7500        Q          0

[891 rows x 7 columns]

In [28]:
new_df.isna().sum()

pclass       0
sex          0
sibsp        0
parch        0
fare         0
embarked     2
relatives    0
dtype: int64

In [29]:
cleandf = df.dropna()
cleandf

     pclass     sex   age  sibsp  parch     fare embarked  relatives
0         3    male  22.0      1      0   7.2500        S          1
1         1  female  38.0      1      0  71.2833        C          1
2         3  female  26.0      0      0   7.9250        S          0
3         1  female  35.0      1      0  53.1000        S          1
4         3    male  35.0      0      0   8.0500        S          0
..      ...     ...   ...    ...    ...      ...      ...        ...
885       3  female  39.0      0      5  29.1250        Q          5
886       2    male  27.0      0      0  13.0000        S          0
887       1  female  19.0      0      0  30.0000        S          0
889       1    male  26.0      0      0  30.0000        C          0
890       3    male  32.0      0      0   7.7500        Q          0

[712 rows x 8 columns]